/**
 * data.js — Начальные данные платформы и их инициализация
 * Содержит дефолтных пользователей, мероприятия, группы.
 */

/* ================================================================
   ДЕФОЛТНЫЕ МЕРОПРИЯТИЯ
   ================================================================ */
const DEFAULT_EVENTS = [
    {
        id:              '1',
        title:           'Региональный этап «Студлидер»',
        date:            '26-28.04.2025',
        time:            '10:00',
        type:            'star',
        description:     'Региональный этап Всероссийского конкурса «Студенческий лидер». Конкурс проводится среди активистов студенческих профсоюзных организаций. В программе: защита проектов, командные игры, мастер-классы от опытных лидеров. Победитель регионального этапа направляется на окружной этап.',
        maxParticipants: 5,
        reserveCount:    2,
        status:          'open',
        requiresForm:    true,
        formFields: [
            { id: 'f1_1', title: 'Ссылка на пост ВКонтакте',          type: 'url',      required: true,  comment: 'Вставьте ссылку на ваш пост, написанный по требованиям конкурса' },
            { id: 'f1_2', title: 'Почему должны выбрать именно вас?', type: 'textarea',  required: true,  comment: 'Расскажите о своих достижениях и мотивации (200–500 слов)' },
        ],
    },
    {
        id:              '2',
        title:           'Всероссийская школа «Лидер будущего»',
        date:            '30.09–07.10.2025',
        time:            '09:00',
        type:            'airplane',
        description:     'Недельная выездная школа для председателей и активистов профбюро вузов. Программа включает тренинги по лидерству, управлению проектами и публичным выступлениям. Участие полностью оплачивается Общероссийским профсоюзом образования.',
        maxParticipants: 3,
        reserveCount:    1,
        status:          'open',
        requiresForm:    true,
        formFields: [
            { id: 'f2_1', title: 'Презентация (файл)',                 type: 'file',     required: true,  comment: 'Загрузите файл .pptx или .pdf' },
            { id: 'f2_2', title: 'Ссылка на резюме или портфолио',     type: 'url',      required: false, comment: 'Необязательно. Например, страница ВКонтакте или Google-документ' },
        ],
    },
    {
        id:              '3',
        title:           'Донорская акция на базе АлтГПУ',
        date:            '15.05.2025',
        time:            '08:00',
        type:            'droplet',
        description:     'Ежегодная донорская акция в партнёрстве с Алтайской краевой станцией переливания крови. Все участники получают справку донора, выходной день и благодарственное письмо от профбюро. Предварительная запись обязательна.',
        maxParticipants: 0,
        reserveCount:    0,
        status:          'open',
        requiresForm:    false,
        formFields:      [],
    },
    {
        id:              '4',
        title:           'Конкурс «Лучший студент АлтГПУ»',
        date:            '20.11.2025',
        time:            '14:00',
        type:            'star',
        description:     'Внутривузовский конкурс, определяющий лучших студентов по номинациям: академические успехи, общественная деятельность, творчество, спорт. Победители награждаются дипломами и ценными призами от профбюро.',
        maxParticipants: 10,
        reserveCount:    3,
        status:          'open',
        requiresForm:    true,
        formFields: [
            { id: 'f4_1', title: 'Эссе о своих достижениях',           type: 'textarea', required: true,  comment: 'Расскажите о достижениях в учёбе и общественной жизни (300–600 слов)' },
            { id: 'f4_2', title: 'Средний балл за последнюю сессию',   type: 'text',     required: true,  comment: 'Например: 4.8' },
        ],
    },
];

/* ================================================================
   ДЕФОЛТНЫЕ УЧАСТНИКИ ГРУППЫ 3215д
   ================================================================ */
const DEFAULT_GROUP_MEMBERS = [
    { id: '1',  name: 'Бесклубова Арина Сергеевна',        username: 'besklubova' },
    { id: '2',  name: 'Ануфриев Артем Александрович',       username: 'anufriev' },
    { id: '3',  name: 'Булатов Иван Григорьевич',           username: 'bulatov' },
    { id: '4',  name: 'Ганюков Данил Андреевич',            username: 'ganyukov' },
    { id: '5',  name: 'Зайберт Константин Валерьевич',      username: 'zaibert' },
    { id: '6',  name: 'Кодылев Андрей Александрович',       username: 'kodylev' },
    { id: '7',  name: 'Копасова Виктория Витальевна',       username: 'kopasova' },
    { id: '8',  name: 'Косенков Денис Алексеевич',          username: 'kosenkov' },
    { id: '9',  name: 'Кузнецов Роман Романович',           username: 'kuznetsov' },
    { id: '10', name: 'Кучеров Денис Евгеньевич',           username: 'kucherov' },
    { id: '11', name: 'Лисименко Алексей Вячеславович',     username: 'lisimenko' },
    { id: '12', name: 'Литягина Анастасия Михайловна',      username: 'lityagina' },
    { id: '13', name: 'Лытарь Алексей Александрович',       username: 'lytar' },
    { id: '14', name: 'Малец Дмитрий Евгеньевич',           username: 'malets' },
    { id: '15', name: 'Пинчук Иван Сергеевич',              username: 'pinchuk' },
    { id: '16', name: 'Рутц Юлия Сергеевна',                username: 'rutts' },
    { id: '17', name: 'Старкова Елизавета Юрьевна',         username: 'starkova' },
    { id: '18', name: 'Удовик Анастасия Александровна',     username: 'udovik' },
    { id: '19', name: 'Фотин Михаил Константинович',        username: 'fotin' },
    { id: '20', name: 'Шинкоренко Владислав Дмитриевич',   username: 'shinkorenko' },
    { id: '21', name: 'Щербаков Никита Сергеевич',          username: 'scherbakov' },
    { id: '22', name: 'Якимов Михаил Александрович',        username: 'yakimov' },
];

/* ================================================================
   ДЕФОЛТНЫЕ ГРУППЫ ИИТИФМО
   ================================================================ */
const DEFAULT_INST_GROUPS = [
    { id: '1',  name: '3524д' }, { id: '2',  name: '3523д' },
    { id: '3',  name: '3522д' }, { id: '4',  name: '3521д' },
    { id: '5',  name: '3515д' }, { id: '6',  name: '3424д' },
    { id: '7',  name: '3423д' }, { id: '8',  name: '3422д' },
    { id: '9',  name: '3421д' }, { id: '10', name: '3415д' },
    { id: '11', name: '3323д' }, { id: '12', name: '3322д' },
    { id: '13', name: '3321д' }, { id: '14', name: '3316д' },
    { id: '15', name: '3315д' }, { id: '16', name: '3223д' },
    { id: '17', name: '3222д' }, { id: '18', name: '3221д' },
    { id: '19', name: '3216д' }, { id: '20', name: '3215д' },
    { id: '21', name: '3123д' }, { id: '22', name: '3122д' },
    { id: '23', name: '3121д' },
];

/* ================================================================
   ДЕФОЛТНЫЕ ПОЛЬЗОВАТЕЛИ (логин / пароль / данные)
   ================================================================ */
const DEFAULT_USERS_LIST = [
    {
        username: 'admin',
        password: 'admin2025ppos',
        isAdmin: true,
        fullName: 'Администратор',
        groupNumber: '',
        role: 'Администратор',
        phone: '',
        email: 'admin@altgpu.ru',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'besklubova',
        password: 'besklubova2025',
        isAdmin: false,
        fullName: 'Бесклубова Арина Сергеевна',
        groupNumber: '3215д',
        role: 'Председатель',
        phone: '+7 (913) 000-00-01',
        email: 'besklubova@altgpu.ru',
        avatarDataUrl: '',
        enrolledEvents: ['1'],
        documents: {},
    },
    {
        username: 'rutts',
        password: 'rutts2025',
        isAdmin: false,
        fullName: 'Рутц Юлия Сергеевна',
        groupNumber: '3215д',
        role: 'Активист профбюро',
        phone: '+7 (913) 000-00-02',
        email: 'rutts@altgpu.ru',
        avatarDataUrl: '',
        enrolledEvents: ['2'],
        documents: {},
    },
    {
        username: 'anufriev',
        password: 'anufriev2025',
        isAdmin: false,
        fullName: 'Ануфриев Артем Александрович',
        groupNumber: '3215д',
        role: 'Активист профбюро',
        phone: '+7 (913) 000-00-03',
        email: 'anufriev@altgpu.ru',
        avatarDataUrl: '',
        enrolledEvents: ['3'],
        documents: {},
    },
    {
        username: 'bulatov',
        password: 'bulatov2025',
        isAdmin: false,
        fullName: 'Булатов Иван Григорьевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'ganyukov',
        password: 'ganyukov2025',
        isAdmin: false,
        fullName: 'Ганюков Данил Андреевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'zaibert',
        password: 'zaibert2025',
        isAdmin: false,
        fullName: 'Зайберт Константин Валерьевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'kodylev',
        password: 'kodylev2025',
        isAdmin: false,
        fullName: 'Кодылев Андрей Александрович',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'kopasova',
        password: 'kopasova2025',
        isAdmin: false,
        fullName: 'Копасова Виктория Витальевна',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'kosenkov',
        password: 'kosenkov2025',
        isAdmin: false,
        fullName: 'Косенков Денис Алексеевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'kuznetsov',
        password: 'kuznetsov2025',
        isAdmin: false,
        fullName: 'Кузнецов Роман Романович',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'kucherov',
        password: 'kucherov2025',
        isAdmin: false,
        fullName: 'Кучеров Денис Евгеньевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'lisimenko',
        password: 'lisimenko2025',
        isAdmin: false,
        fullName: 'Лисименко Алексей Вячеславович',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'lityagina',
        password: 'lityagina2025',
        isAdmin: false,
        fullName: 'Литягина Анастасия Михайловна',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'lytar',
        password: 'lytar2025',
        isAdmin: false,
        fullName: 'Лытарь Алексей Александрович',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'malets',
        password: 'malets2025',
        isAdmin: false,
        fullName: 'Малец Дмитрий Евгеньевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'pinchuk',
        password: 'pinchuk2025',
        isAdmin: false,
        fullName: 'Пинчук Иван Сергеевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'starkova',
        password: 'starkova2025',
        isAdmin: false,
        fullName: 'Старкова Елизавета Юрьевна',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'udovik',
        password: 'udovik2025',
        isAdmin: false,
        fullName: 'Удовик Анастасия Александровна',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'fotin',
        password: 'fotin2025',
        isAdmin: false,
        fullName: 'Фотин Михаил Константинович',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'shinkorenko',
        password: 'shinkorenko2025',
        isAdmin: false,
        fullName: 'Шинкоренко Владислав Дмитриевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'scherbakov',
        password: 'scherbakov2025',
        isAdmin: false,
        fullName: 'Щербаков Никита Сергеевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'yakimov',
        password: 'yakimov2025',
        isAdmin: false,
        fullName: 'Якимов Михаил Александрович',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    // --- 3221д ---
    { username:'borisova',     password:'borisova2025',     isAdmin:false, fullName:'Борисова Татьяна Сергеевна',           groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'brattseva',    password:'brattseva2025',    isAdmin:false, fullName:'Братцева Виктория Андреевна',          groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'burov3221',    password:'burov32212025',    isAdmin:false, fullName:'Буров Иван Максимович',                groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'volzhina',     password:'volzhina2025',     isAdmin:false, fullName:'Волжина Анастасия Андреевна',          groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'gokshteter',   password:'gokshteter2025',   isAdmin:false, fullName:'Гокштетер Анастасия Матвеевна',        groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'ilina',        password:'ilina2025',        isAdmin:false, fullName:'Ильина Виктория Алексеевна',           groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'kapustin',     password:'kapustin2025',     isAdmin:false, fullName:'Капустин Богдан Вадимович',            groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'komzarova',    password:'komzarova2025',    isAdmin:false, fullName:'Комзарова Лилия Сергеевна',            groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'kuzub',        password:'kuzub2025',        isAdmin:false, fullName:'Кузуб Виктория Степановна',            groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'medvedeva3221',password:'medvedeva32212025',isAdmin:false, fullName:'Медведева Валерия Вячеславовна',       groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'nefedova',     password:'nefedova2025',     isAdmin:false, fullName:'Нефедова Екатерина Аркадьевна',        groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'onoprienko',   password:'onoprienko2025',   isAdmin:false, fullName:'Оноприенко Екатерина Александровна',  groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'prodolyakina', password:'prodolyakina2025', isAdmin:false, fullName:'Продолякина Анастасия Алексеевна',    groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'prokhnau',     password:'prokhnau2025',     isAdmin:false, fullName:'Прохнау Елизавета Владимировна',       groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'rolzing',      password:'rolzing2025',      isAdmin:false, fullName:'Рользинг Алина Юрьевна',               groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'torlopova',    password:'torlopova2025',    isAdmin:false, fullName:'Торлопова Дарья Александровна',        groupNumber:'3221д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    // --- 3315д ---
    { username:'bespalov',     password:'bespalov2025',     isAdmin:false, fullName:'Беспалов Никита Алексеевич',           groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'glukhonemykh', password:'glukhonemykh2025', isAdmin:false, fullName:'Глухонемых Павел Дмитриевич',          groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'zharonkin',    password:'zharonkin2025',    isAdmin:false, fullName:'Жаронкин Иван Андреевич',              groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'klepikov',     password:'klepikov2025',     isAdmin:false, fullName:'Клепиков Данил Александрович',         groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'klimov',       password:'klimov2025',       isAdmin:false, fullName:'Климов Артём Дмитриевич',              groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'kodirov',      password:'kodirov2025',      isAdmin:false, fullName:'Кодиров Халимджон Абдукодирович',      groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'logvinova',    password:'logvinova2025',    isAdmin:false, fullName:'Логвинова Елена Андреевна',            groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'lyutaev',      password:'lyutaev2025',      isAdmin:false, fullName:'Лютаев Степан Евгеньевич',             groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'maslova',      password:'maslova2025',      isAdmin:false, fullName:'Маслова Елизавета Андреевна',          groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'medvedeva3315',password:'medvedeva33152025',isAdmin:false, fullName:'Медведева Вероника Вячеславовна',      groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'miev',         password:'miev2025',         isAdmin:false, fullName:'Миев Сергей Дмитриевич',               groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'pigareva',     password:'pigareva2025',     isAdmin:false, fullName:'Пигарева Дарья Сергеевна',             groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'sergeev',      password:'sergeev2025',      isAdmin:false, fullName:'Сергеев Евгений Александрович',        groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'sergeenko',    password:'sergeenko2025',    isAdmin:false, fullName:'Сергеенко Кирилл Сергеевич',           groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'troshev',      password:'troshev2025',      isAdmin:false, fullName:'Трошев Александр Сергеевич',           groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'shilyaev',     password:'shilyaev2025',     isAdmin:false, fullName:'Шиляев Алексей Дмитриевич',            groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'engraf',       password:'engraf2025',       isAdmin:false, fullName:'Энграф Даниил Юрьевич',                groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'yaremenko',    password:'yaremenko2025',    isAdmin:false, fullName:'Ярёменко Иван Николаевич',             groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'yarovoy',      password:'yarovoy2025',      isAdmin:false, fullName:'Яровой Алексей Максимович',            groupNumber:'3315д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    // --- 3321д ---
    { username:'anegov',       password:'anegov2025',       isAdmin:false, fullName:'Анегов Владимир Евгеньевич',           groupNumber:'3321д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'bersh',        password:'bersh2025',        isAdmin:false, fullName:'Берш Вероника Сергеевна',              groupNumber:'3321д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'garkushin',    password:'garkushin2025',    isAdmin:false, fullName:'Гаркушин Степан Алексеевич',           groupNumber:'3321д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'zhabina',      password:'zhabina2025',      isAdmin:false, fullName:'Жабина Ангелина Ивановна',             groupNumber:'3321д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'zagainova',    password:'zagainova2025',    isAdmin:false, fullName:'Загайнова Софья Алексеевна',           groupNumber:'3321д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'kabanov',      password:'kabanov2025',      isAdmin:false, fullName:'Кабанов Михаил Алексеевич',            groupNumber:'3321д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'klimova',      password:'klimova2025',      isAdmin:false, fullName:'Климова Анастасия Евгеньевна',         groupNumber:'3321д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'kudryavtseva', password:'kudryavtseva2025', isAdmin:false, fullName:'Кудрявцева Елизавета Александровна',  groupNumber:'3321д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'martyshkina',  password:'martyshkina2025',  isAdmin:false, fullName:'Мартышкина Маргарита Николаевна',      groupNumber:'3321д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'masaeva',      password:'masaeva2025',      isAdmin:false, fullName:'Масаева Ксения Александровна',         groupNumber:'3321д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'pronevskaya',  password:'pronevskaya2025',  isAdmin:false, fullName:'Проневская Ольга Александровна',       groupNumber:'3321д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'syreeva',      password:'syreeva2025',      isAdmin:false, fullName:'Сыреева Мария Валентиновна',           groupNumber:'3321д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'fesik',        password:'fesik2025',        isAdmin:false, fullName:'Фесик Наталья Александровна',          groupNumber:'3321д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    // --- 3322д ---
    { username:'astanovka',    password:'astanovka2025',    isAdmin:false, fullName:'Астановка Ярослав Олегович',           groupNumber:'3322д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'kotovschikov', password:'kotovschikov2025', isAdmin:false, fullName:'Котовщиков Павел Александрович',       groupNumber:'3322д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'luschay',      password:'luschay2025',      isAdmin:false, fullName:'Лущай Данил Витальевич',               groupNumber:'3322д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'moldavsky',    password:'moldavsky2025',    isAdmin:false, fullName:'Молдавский Владислав Сергеевич',       groupNumber:'3322д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'sarapulov',    password:'sarapulov2025',    isAdmin:false, fullName:'Сарапулов Даниил Алексеевич',          groupNumber:'3322д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'senachin',     password:'senachin2025',     isAdmin:false, fullName:'Сеначин Владимир Андреевич',           groupNumber:'3322д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'sukhorukova',  password:'sukhorukova2025',  isAdmin:false, fullName:'Сухорукова Яна Евгеньевна',            groupNumber:'3322д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
    { username:'cherepanov',   password:'cherepanov2025',   isAdmin:false, fullName:'Черепанов Олег Александрович',         groupNumber:'3322д', role:'Студент', phone:'', email:'', avatarDataUrl:'', enrolledEvents:[], documents:{} },
];

/* ================================================================
   ИНСТИТУТЫ И ГРУППЫ АлтГПУ
   ================================================================ */
const INSTITUTES = [
    { id: 'iitifmo', name: 'ИИТиФМО'  },
    { id: 'liin',    name: 'ЛИИН'      },
    { id: 'ipip',    name: 'ИПиП'      },
    { id: 'iiskip',  name: 'ИИСКиП'   },
    { id: 'ifkis',   name: 'ИФКиС'    },
    { id: 'ifimk',   name: 'ИФиМК'    },
    { id: 'college', name: 'Колледж'   },
];

const INSTITUTE_GROUPS = {
    'ЛИИН': [
        '1121д','1122д','1123д','1124д','1125д','1126д','1127д','1129д','1211д',
        '1221д','1222д','1223д','1224д','1225д','1226д','1227д','1228д','1311д',
        '1321д','1322д','1323д','1324д','1325д','1326д','1327д','1411д','1421д',
        '1422д','1423д','1424д','1425д','1426д','1427д','1428д','1511д','1512д',
        '1521д','1522д','1523д','1524д','1525д','1526д','1527д','1528д','1529д',
    ],
    'ИПиП': [
        '2168д','2268д','2368д','2468д','2568д','2122д','2125д','2126д','2127д',
        '2211д','2213д','2214д','2222д','2225д','2226д','2227д','2311д','2313д',
        '2314д','2322д','2325д','2326д','2327д','2411д','2413д','2414д','2422д',
        '2425д','2426д','2427д','2511д','2513д','2514д','2522д','2525д','2526д','2527д',
    ],
    'ИИТиФМО': [
        '3121д','3122д','3123д','3215д','3216д','3221д','3222д','3223д','3315д',
        '3316д','3321д','3322д','3323д','3415д','3421д','3422д','3423д','3424д',
        '3515д','3521д','3522д','3523д','3524д',
    ],
    'ИИСКиП': [
        '6121д','6122д','6123д','6124д','6222д','6223д','6224д','6321д','6323д',
        '6324д','6421д','6422д','6424д','6521д','6522д','6523д','6524д','6525д',
        '6526д','6527д',
    ],
    'ИФКиС': [
        '4121д','4122д','4123д','4211д','4221д','4222д','4223д','4311д','4321д',
        '4322д','4323д','4411д','4421д','4422д','4423д','4511д','4521д','4522д','4523д',
    ],
    'ИФиМК': [
        '5121д','5123д','5124д','5211д','5221д','5222д','5224д','5225д','5313д',
        '5321д','5323д','5324д','5325д','5421д','5422д','5423д','5424д','5521д',
        '5522д','5523д','5524д',
    ],
    'Колледж': [
        '8312д','8321д','8322д','8411д','8412д','8421д','8422д',
        'ГД511д','ГД521д','Де511д','ДО511д','ДО512д','ДО521д',
        'ИСИП511д','ПНК511д','ПНК512д','ПНК521д','ПНК522д',
        'Т511д','Ю511д','Ю512д','Ю521д','Ю522д',
    ],
};

/* ================================================================
   УЧАСТНИКИ ГРУПП ИИТиФМО
   ================================================================ */
const DEFAULT_GROUP_MEMBERS_MAP = {
    '3215д': DEFAULT_GROUP_MEMBERS,
    '3221д': [
        { id: 'g2_1',  name: 'Борисова Татьяна Сергеевна',           username: 'borisova'      },
        { id: 'g2_2',  name: 'Братцева Виктория Андреевна',           username: 'brattseva'     },
        { id: 'g2_3',  name: 'Буров Иван Максимович',                 username: 'burov3221'     },
        { id: 'g2_4',  name: 'Волжина Анастасия Андреевна',           username: 'volzhina'      },
        { id: 'g2_5',  name: 'Гокштетер Анастасия Матвеевна',         username: 'gokshteter'    },
        { id: 'g2_6',  name: 'Ильина Виктория Алексеевна',            username: 'ilina'         },
        { id: 'g2_7',  name: 'Капустин Богдан Вадимович',             username: 'kapustin'      },
        { id: 'g2_8',  name: 'Комзарова Лилия Сергеевна',             username: 'komzarova'     },
        { id: 'g2_9',  name: 'Кузуб Виктория Степановна',             username: 'kuzub'         },
        { id: 'g2_10', name: 'Медведева Валерия Вячеславовна',         username: 'medvedeva3221' },
        { id: 'g2_11', name: 'Нефедова Екатерина Аркадьевна',          username: 'nefedova'      },
        { id: 'g2_12', name: 'Оноприенко Екатерина Александровна',     username: 'onoprienko'    },
        { id: 'g2_13', name: 'Продолякина Анастасия Алексеевна',       username: 'prodolyakina'  },
        { id: 'g2_14', name: 'Прохнау Елизавета Владимировна',         username: 'prokhnau'      },
        { id: 'g2_15', name: 'Рользинг Алина Юрьевна',                 username: 'rolzing'       },
        { id: 'g2_16', name: 'Торлопова Дарья Александровна',          username: 'torlopova'     },
    ],
    '3315д': [
        { id: 'g3_1',  name: 'Беспалов Никита Алексеевич',            username: 'bespalov'      },
        { id: 'g3_2',  name: 'Глухонемых Павел Дмитриевич',           username: 'glukhonemykh'  },
        { id: 'g3_3',  name: 'Жаронкин Иван Андреевич',               username: 'zharonkin'     },
        { id: 'g3_4',  name: 'Клепиков Данил Александрович',          username: 'klepikov'      },
        { id: 'g3_5',  name: 'Климов Артём Дмитриевич',               username: 'klimov'        },
        { id: 'g3_6',  name: 'Кодиров Халимджон Абдукодирович',       username: 'kodirov'       },
        { id: 'g3_7',  name: 'Логвинова Елена Андреевна',             username: 'logvinova'     },
        { id: 'g3_8',  name: 'Лютаев Степан Евгеньевич',              username: 'lyutaev'       },
        { id: 'g3_9',  name: 'Маслова Елизавета Андреевна',           username: 'maslova'       },
        { id: 'g3_10', name: 'Медведева Вероника Вячеславовна',        username: 'medvedeva3315' },
        { id: 'g3_11', name: 'Миев Сергей Дмитриевич',                username: 'miev'          },
        { id: 'g3_12', name: 'Пигарева Дарья Сергеевна',              username: 'pigareva'      },
        { id: 'g3_13', name: 'Сергеев Евгений Александрович',         username: 'sergeev'       },
        { id: 'g3_14', name: 'Сергеенко Кирилл Сергеевич',            username: 'sergeenko'     },
        { id: 'g3_15', name: 'Трошев Александр Сергеевич',            username: 'troshev'       },
        { id: 'g3_16', name: 'Шиляев Алексей Дмитриевич',             username: 'shilyaev'      },
        { id: 'g3_17', name: 'Энграф Даниил Юрьевич',                 username: 'engraf'        },
        { id: 'g3_18', name: 'Ярёменко Иван Николаевич',              username: 'yaremenko'     },
        { id: 'g3_19', name: 'Яровой Алексей Максимович',             username: 'yarovoy'       },
    ],
    '3321д': [
        { id: 'g4_1',  name: 'Анегов Владимир Евгеньевич',            username: 'anegov'        },
        { id: 'g4_2',  name: 'Берш Вероника Сергеевна',               username: 'bersh'         },
        { id: 'g4_3',  name: 'Гаркушин Степан Алексеевич',            username: 'garkushin'     },
        { id: 'g4_4',  name: 'Жабина Ангелина Ивановна',              username: 'zhabina'       },
        { id: 'g4_5',  name: 'Загайнова Софья Алексеевна',            username: 'zagainova'     },
        { id: 'g4_6',  name: 'Кабанов Михаил Алексеевич',             username: 'kabanov'       },
        { id: 'g4_7',  name: 'Климова Анастасия Евгеньевна',          username: 'klimova'       },
        { id: 'g4_8',  name: 'Кудрявцева Елизавета Александровна',    username: 'kudryavtseva'  },
        { id: 'g4_9',  name: 'Мартышкина Маргарита Николаевна',       username: 'martyshkina'   },
        { id: 'g4_10', name: 'Масаева Ксения Александровна',          username: 'masaeva'       },
        { id: 'g4_11', name: 'Проневская Ольга Александровна',        username: 'pronevskaya'   },
        { id: 'g4_12', name: 'Сыреева Мария Валентиновна',            username: 'syreeva'       },
        { id: 'g4_13', name: 'Фесик Наталья Александровна',           username: 'fesik'         },
    ],
    '3322д': [
        { id: 'g5_1',  name: 'Астановка Ярослав Олегович',            username: 'astanovka'     },
        { id: 'g5_2',  name: 'Котовщиков Павел Александрович',        username: 'kotovschikov'  },
        { id: 'g5_3',  name: 'Лущай Данил Витальевич',                username: 'luschay'       },
        { id: 'g5_4',  name: 'Молдавский Владислав Сергеевич',        username: 'moldavsky'     },
        { id: 'g5_5',  name: 'Сарапулов Даниил Алексеевич',           username: 'sarapulov'     },
        { id: 'g5_6',  name: 'Сеначин Владимир Андреевич',            username: 'senachin'      },
        { id: 'g5_7',  name: 'Сухорукова Яна Евгеньевна',             username: 'sukhorukova'   },
        { id: 'g5_8',  name: 'Черепанов Олег Александрович',          username: 'cherepanov'    },
    ],
};

/* ================================================================
   ИНИЦИАЛИЗАЦИЯ — заполнение хранилища дефолтными данными
   ================================================================ */
function initDefaultData() {
    // Пользователи — только если совсем пусто
    const existingUsers = getUsers();
    if (Object.keys(existingUsers).length === 0) {
        const usersMap = {};
        DEFAULT_USERS_LIST.forEach(u => {
            usersMap[u.username] = { ...u };
        });
        saveUsers(usersMap);
    }

    // Мероприятия
    if (!getEventsFromStorage()) {
        saveEventsToStorage(DEFAULT_EVENTS);
    }

    // Участники группы
    if (!getGroupMembersFromStorage()) {
        saveGroupMembersToStorage(DEFAULT_GROUP_MEMBERS);
    }

    // Группы института
    if (!getInstGroupsFromStorage()) {
        saveInstGroupsToStorage(DEFAULT_INST_GROUPS);
    }
}
