/**
 * data.js — Начальные данные платформы и их инициализация
 * Содержит дефолтных пользователей, мероприятия, группы.
 */

/* ================================================================
   ДЕФОЛТНЫЕ МЕРОПРИЯТИЯ
   ================================================================ */
const DEFAULT_EVENTS = [
    {
        id:              '1',
        title:           'Региональный этап «Студлидер»',
        date:            '26-28.04.2025',
        time:            '10:00',
        type:            'star',
        description:     'Региональный этап Всероссийского конкурса «Студенческий лидер». Конкурс проводится среди активистов студенческих профсоюзных организаций. В программе: защита проектов, командные игры, мастер-классы от опытных лидеров. Победитель регионального этапа направляется на окружной этап.',
        maxParticipants: 5,
        reserveCount:    2,
        status:          'open',
        requiresForm:    true,
        formFields: [
            { id: 'f1_1', title: 'Ссылка на пост ВКонтакте',          type: 'url',      required: true,  comment: 'Вставьте ссылку на ваш пост, написанный по требованиям конкурса' },
            { id: 'f1_2', title: 'Почему должны выбрать именно вас?', type: 'textarea',  required: true,  comment: 'Расскажите о своих достижениях и мотивации (200–500 слов)' },
        ],
    },
    {
        id:              '2',
        title:           'Всероссийская школа «Лидер будущего»',
        date:            '30.09–07.10.2025',
        time:            '09:00',
        type:            'airplane',
        description:     'Недельная выездная школа для председателей и активистов профбюро вузов. Программа включает тренинги по лидерству, управлению проектами и публичным выступлениям. Участие полностью оплачивается Общероссийским профсоюзом образования.',
        maxParticipants: 3,
        reserveCount:    1,
        status:          'open',
        requiresForm:    true,
        formFields: [
            { id: 'f2_1', title: 'Презентация (файл)',                 type: 'file',     required: true,  comment: 'Загрузите файл .pptx или .pdf' },
            { id: 'f2_2', title: 'Ссылка на резюме или портфолио',     type: 'url',      required: false, comment: 'Необязательно. Например, страница ВКонтакте или Google-документ' },
        ],
    },
    {
        id:              '3',
        title:           'Донорская акция на базе АлтГПУ',
        date:            '15.05.2025',
        time:            '08:00',
        type:            'droplet',
        description:     'Ежегодная донорская акция в партнёрстве с Алтайской краевой станцией переливания крови. Все участники получают справку донора, выходной день и благодарственное письмо от профбюро. Предварительная запись обязательна.',
        maxParticipants: 0,
        reserveCount:    0,
        status:          'open',
        requiresForm:    false,
        formFields:      [],
    },
    {
        id:              '4',
        title:           'Конкурс «Лучший студент АлтГПУ»',
        date:            '20.11.2025',
        time:            '14:00',
        type:            'star',
        description:     'Внутривузовский конкурс, определяющий лучших студентов по номинациям: академические успехи, общественная деятельность, творчество, спорт. Победители награждаются дипломами и ценными призами от профбюро.',
        maxParticipants: 10,
        reserveCount:    3,
        status:          'open',
        requiresForm:    true,
        formFields: [
            { id: 'f4_1', title: 'Эссе о своих достижениях',           type: 'textarea', required: true,  comment: 'Расскажите о достижениях в учёбе и общественной жизни (300–600 слов)' },
            { id: 'f4_2', title: 'Средний балл за последнюю сессию',   type: 'text',     required: true,  comment: 'Например: 4.8' },
        ],
    },
];

/* ================================================================
   ДЕФОЛТНЫЕ УЧАСТНИКИ ГРУППЫ 3215д
   ================================================================ */
const DEFAULT_GROUP_MEMBERS = [
    { id: '1',  name: 'Бесклубова Арина Сергеевна',        username: 'besklubova' },
    { id: '2',  name: 'Ануфриев Артем Александрович',       username: 'anufriev' },
    { id: '3',  name: 'Булатов Иван Григорьевич',           username: 'bulatov' },
    { id: '4',  name: 'Ганюков Данил Андреевич',            username: 'ganyukov' },
    { id: '5',  name: 'Зайберт Константин Валерьевич',      username: 'zaibert' },
    { id: '6',  name: 'Кодылев Андрей Александрович',       username: 'kodylev' },
    { id: '7',  name: 'Копасова Виктория Витальевна',       username: 'kopasova' },
    { id: '8',  name: 'Косенков Денис Алексеевич',          username: 'kosenkov' },
    { id: '9',  name: 'Кузнецов Роман Романович',           username: 'kuznetsov' },
    { id: '10', name: 'Кучеров Денис Евгеньевич',           username: 'kucherov' },
    { id: '11', name: 'Лисименко Алексей Вячеславович',     username: 'lisimenko' },
    { id: '12', name: 'Литягина Анастасия Михайловна',      username: 'lityagina' },
    { id: '13', name: 'Лытарь Алексей Александрович',       username: 'lytar' },
    { id: '14', name: 'Малец Дмитрий Евгеньевич',           username: 'malets' },
    { id: '15', name: 'Пинчук Иван Сергеевич',              username: 'pinchuk' },
    { id: '16', name: 'Рутц Юлия Сергеевна',                username: 'rutts' },
    { id: '17', name: 'Старкова Елизавета Юрьевна',         username: 'starkova' },
    { id: '18', name: 'Удовик Анастасия Александровна',     username: 'udovik' },
    { id: '19', name: 'Фотин Михаил Константинович',        username: 'fotin' },
    { id: '20', name: 'Шинкоренко Владислав Дмитриевич',   username: 'shinkorenko' },
    { id: '21', name: 'Щербаков Никита Сергеевич',          username: 'scherbakov' },
    { id: '22', name: 'Якимов Михаил Александрович',        username: 'yakimov' },
];

/* ================================================================
   ДЕФОЛТНЫЕ ГРУППЫ ИИТИФМО
   ================================================================ */
const DEFAULT_INST_GROUPS = [
    { id: '1',  name: '3524д' }, { id: '2',  name: '3523д' },
    { id: '3',  name: '3522д' }, { id: '4',  name: '3521д' },
    { id: '5',  name: '3515д' }, { id: '6',  name: '3424д' },
    { id: '7',  name: '3423д' }, { id: '8',  name: '3422д' },
    { id: '9',  name: '3421д' }, { id: '10', name: '3415д' },
    { id: '11', name: '3323д' }, { id: '12', name: '3322д' },
    { id: '13', name: '3321д' }, { id: '14', name: '3316д' },
    { id: '15', name: '3315д' }, { id: '16', name: '3223д' },
    { id: '17', name: '3222д' }, { id: '18', name: '3221д' },
    { id: '19', name: '3216д' }, { id: '20', name: '3215д' },
    { id: '21', name: '3123д' }, { id: '22', name: '3122д' },
    { id: '23', name: '3121д' },
];

/* ================================================================
   ДЕФОЛТНЫЕ ПОЛЬЗОВАТЕЛИ (логин / пароль / данные)
   ================================================================ */
const DEFAULT_USERS_LIST = [
    {
        username: 'admin',
        password: 'admin2025ppos',
        isAdmin: true,
        fullName: 'Администратор',
        groupNumber: '',
        role: 'Администратор',
        phone: '',
        email: 'admin@altgpu.ru',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'besklubova',
        password: 'besklubova2025',
        isAdmin: false,
        fullName: 'Бесклубова Арина Сергеевна',
        groupNumber: '3215д',
        role: 'Председатель',
        phone: '+7 (913) 000-00-01',
        email: 'besklubova@altgpu.ru',
        avatarDataUrl: '',
        enrolledEvents: ['1'],
        documents: {},
    },
    {
        username: 'rutts',
        password: 'rutts2025',
        isAdmin: false,
        fullName: 'Рутц Юлия Сергеевна',
        groupNumber: '3215д',
        role: 'Активист профбюро',
        phone: '+7 (913) 000-00-02',
        email: 'rutts@altgpu.ru',
        avatarDataUrl: '',
        enrolledEvents: ['2'],
        documents: {},
    },
    {
        username: 'anufriev',
        password: 'anufriev2025',
        isAdmin: false,
        fullName: 'Ануфриев Артем Александрович',
        groupNumber: '3215д',
        role: 'Активист профбюро',
        phone: '+7 (913) 000-00-03',
        email: 'anufriev@altgpu.ru',
        avatarDataUrl: '',
        enrolledEvents: ['3'],
        documents: {},
    },
    {
        username: 'bulatov',
        password: 'bulatov2025',
        isAdmin: false,
        fullName: 'Булатов Иван Григорьевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'ganyukov',
        password: 'ganyukov2025',
        isAdmin: false,
        fullName: 'Ганюков Данил Андреевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'zaibert',
        password: 'zaibert2025',
        isAdmin: false,
        fullName: 'Зайберт Константин Валерьевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'kodylev',
        password: 'kodylev2025',
        isAdmin: false,
        fullName: 'Кодылев Андрей Александрович',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'kopasova',
        password: 'kopasova2025',
        isAdmin: false,
        fullName: 'Копасова Виктория Витальевна',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'kosenkov',
        password: 'kosenkov2025',
        isAdmin: false,
        fullName: 'Косенков Денис Алексеевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'kuznetsov',
        password: 'kuznetsov2025',
        isAdmin: false,
        fullName: 'Кузнецов Роман Романович',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'kucherov',
        password: 'kucherov2025',
        isAdmin: false,
        fullName: 'Кучеров Денис Евгеньевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'lisimenko',
        password: 'lisimenko2025',
        isAdmin: false,
        fullName: 'Лисименко Алексей Вячеславович',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'lityagina',
        password: 'lityagina2025',
        isAdmin: false,
        fullName: 'Литягина Анастасия Михайловна',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'lytar',
        password: 'lytar2025',
        isAdmin: false,
        fullName: 'Лытарь Алексей Александрович',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'malets',
        password: 'malets2025',
        isAdmin: false,
        fullName: 'Малец Дмитрий Евгеньевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'pinchuk',
        password: 'pinchuk2025',
        isAdmin: false,
        fullName: 'Пинчук Иван Сергеевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'starkova',
        password: 'starkova2025',
        isAdmin: false,
        fullName: 'Старкова Елизавета Юрьевна',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'udovik',
        password: 'udovik2025',
        isAdmin: false,
        fullName: 'Удовик Анастасия Александровна',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'fotin',
        password: 'fotin2025',
        isAdmin: false,
        fullName: 'Фотин Михаил Константинович',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'shinkorenko',
        password: 'shinkorenko2025',
        isAdmin: false,
        fullName: 'Шинкоренко Владислав Дмитриевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'scherbakov',
        password: 'scherbakov2025',
        isAdmin: false,
        fullName: 'Щербаков Никита Сергеевич',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
    {
        username: 'yakimov',
        password: 'yakimov2025',
        isAdmin: false,
        fullName: 'Якимов Михаил Александрович',
        groupNumber: '3215д',
        role: 'Студент',
        phone: '',
        email: '',
        avatarDataUrl: '',
        enrolledEvents: [],
        documents: {},
    },
];

/* ================================================================
   ИНИЦИАЛИЗАЦИЯ — заполнение хранилища дефолтными данными
   ================================================================ */
function initDefaultData() {
    // Пользователи — только если совсем пусто
    const existingUsers = getUsers();
    if (Object.keys(existingUsers).length === 0) {
        const usersMap = {};
        DEFAULT_USERS_LIST.forEach(u => {
            usersMap[u.username] = { ...u };
        });
        saveUsers(usersMap);
    }

    // Мероприятия
    if (!getEventsFromStorage()) {
        saveEventsToStorage(DEFAULT_EVENTS);
    }

    // Участники группы
    if (!getGroupMembersFromStorage()) {
        saveGroupMembersToStorage(DEFAULT_GROUP_MEMBERS);
    }

    // Группы института
    if (!getInstGroupsFromStorage()) {
        saveInstGroupsToStorage(DEFAULT_INST_GROUPS);
    }
}
